INSERT INTO vetclinic.types(name) VALUES('dog');
INSERT INTO vetclinic.types(name) VALUES('goat');
INSERT INTO vetclinic.types(name) VALUES('pig');
INSERT INTO vetclinic.types(name) VALUES('sheep');
INSERT INTO vetclinic.types(name) VALUES('cattle');
INSERT INTO vetclinic.types(name) VALUES('cat');
INSERT INTO vetclinic.types(name) VALUES('canary');
INSERT INTO vetclinic.types(name) VALUES('duck');
INSERT INTO vetclinic.types(name) VALUES('ferret');
INSERT INTO vetclinic.types(name) VALUES('rabbit');
INSERT INTO vetclinic.types(name) VALUES('fancy rat');
INSERT INTO vetclinic.types(name) VALUES('mink');
INSERT INTO vetclinic.types(name) VALUES('hedgehogs');
INSERT INTO vetclinic.types(name) VALUES('goldfish');
INSERT INTO vetclinic.types(name) VALUES('alpaca');
