CREATE TABLE IF NOT EXISTS vetclinic.owners
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(200) NOT NULL,
    last_name varchar(200) NOT NULL,
    middle_name varchar(200),
    age varchar(200)  NOT NULL,
    address varchar(200)  NOT NULL,
    telephone varchar(200)  NOT NULL,
    CONSTRAINT owners_pkey PRIMARY KEY (id)
    )