CREATE TABLE IF NOT EXISTS vetclinic.vaccinations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(200)  NOT NULL,
    vaccination_date date NOT NULL,
    CONSTRAINT vaccinations_pkey PRIMARY KEY (id)
    )