CREATE TABLE IF NOT EXISTS vetclinic.pets
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(200)  NOT NULL,
    type_id bigint NOT NULL,
    owner_id bigint NOT NULL,
    vaccination_id bigint NOT NULL,
    birth_date date NOT NULL,
    CONSTRAINT pets_pkey PRIMARY KEY (id),
    CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id)
    REFERENCES vetclinic.owners (id),
    CONSTRAINT fk_pets_types FOREIGN KEY (type_id)
    REFERENCES vetclinic.types (id),
    CONSTRAINT fk_pets_vaccinations FOREIGN KEY (vaccination_id)
    REFERENCES vetclinic.vaccinations (id)
    )