CREATE TABLE IF NOT EXISTS vetclinic.vets
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    firstName varchar(255) NOT NULL,
    lastName varchar(255) NOT NULL,
    middleName varchar(255) NOT NULL,
    age integer NOT NULL,
    CONSTRAINT vets_pkey PRIMARY KEY (id)
    )