CREATE TABLE IF NOT EXISTS vetclinic.bookings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    day_of_week smallint NOT NULL,
    pet_id bigint NOT NULL,
    vet_id bigint NOT NULL,
    date date NOT NULL,
    CONSTRAINT bookings_pkey PRIMARY KEY (id),
    CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id)
    REFERENCES vetclinic.pets (id),
    CONSTRAINT fk_visits_vets FOREIGN KEY (vet_id)
    REFERENCES vetclinic.vets (id)
    )