CREATE TABLE IF NOT EXISTS vetclinic.visits
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date date NOT NULL,
    description varchar(255) NOT NULL,
    pet_id bigint NOT NULL,
    vet_id bigint NOT NULL,
    CONSTRAINT visits_pkey PRIMARY KEY (id),
    CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id)
    REFERENCES vetclinic.pets (id),
    CONSTRAINT fk_visits_vets FOREIGN KEY (vet_id)
    REFERENCES vetclinic.vets (id)
    )